---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Media
- type: directory
  path: content/assets
  label: assets
  create: all
  match: "**/*"
- type: directory
  path: uploads
  label: uploads
  create: all
  match: "**/*"
- type: heading
  label: Pages
- type: directory
  path: content/posts
  label: posts
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Settings
- type: document
  path: gatsby-config.js
  label: gatsby-config.js
  match: "**/*"
- type: document
  path: package.json
  label: package.json
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:-:year:-:month:-:day:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
